#!/usr/bin/env bash

set -euo pipefail

SRC=$(realpath "${0%/*}")
export ROOT="$SRC/../.."

export LC_ALL=C.UTF-8
export DISPLAY=":$1"

export HOME="$WORKDIR/home.$$.$SRANDOM"
mkdir "$HOME"

export NVIM_LOG_FILE="$HOME/nvim.log"
export XDG_CONFIG_HOME="$HOME/config"
export XDG_DATA_HOME="$HOME/share"
export XDG_STATE_HOME="$HOME/state"

unset VIMRUNTIME VIMINIT

args=(
    -ah
    -fa "DejaVu Sans Mono"
    -fs 18
    -fg white
    -bg black
    -geometry 80x30
    -e
    faketime '2000-01-01 10:00:00'
    nvim --clean -c "source $SRC/main.lua"
)

cp "$SRC/fake-tests.sh" "$HOME/run-tests"
cd "$HOME"

set -x
exec xterm "${args[@]}"
