#!/usr/bin/env bash

set -euo pipefail

TEXT="$(realpath "$1")"
CONFIG="$(realpath "$2")"

OUTPUT=doc/ceramicist.txt
TARGET="$PWD/$OUTPUT"


WORKDIR=$(mktemp -d)
test -d "$WORKDIR"

cd "$WORKDIR"
mkdir doc

cleanup() {
    rm -r "$WORKDIR"
}

trap cleanup EXIT


set -x

# Extract default config object.
sed < "$CONFIG" > config '
    1i```lua
    1i{
    1,/local config = /d
    s/^    //
    /^\}/ {
        a```
        q
    }
'

sed < "$TEXT" '
    /<!-- panvimdoc-include-config -->/r config
    s/<kbd>\(\S\+\)<\/kbd>/\\<\1>/g
    s/\[\S\+\]\[h\.\(\S\+\)\]/|\1|/g
    s/`:\([a-z!]\+\)`/|:\1|/g
' | panvimdoc \
    --input-file - \
    --project-name ceramicist \
    --shift-heading-level-by -1 \
    --description "Command Runner"


# Remove footer and trailing spaces.
sed -i '/^Generated by panvimdoc/,+1d; s/\s\+$//' "$OUTPUT"

cp "$OUTPUT" "$TARGET"
